"""empty message

Revision ID: 6d7084f4702f
Revises: ed53a3d1cfda
Create Date: 2021-12-13 23:26:01.251657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7084f4702f'
down_revision = 'ed53a3d1cfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
