"""empty message

Revision ID: a85172149df7
Revises: 44e4db9abfd6
Create Date: 2021-12-13 18:33:29.367278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85172149df7'
down_revision = '44e4db9abfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password_hash_confirmation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash_confirmation')
    op.drop_column('users', 'confirm_email')
    # ### end Alembic commands ###
