"""empty message

Revision ID: ac76569e1c17
Revises: a85172149df7
Create Date: 2021-12-13 20:45:40.663113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac76569e1c17'
down_revision = 'a85172149df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paths_end_date', table_name='paths')
    op.drop_index('ix_paths_initial_date', table_name='paths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paths_initial_date', 'paths', ['initial_date'], unique=False)
    op.create_index('ix_paths_end_date', 'paths', ['end_date'], unique=False)
    # ### end Alembic commands ###
