"""empty message

Revision ID: b609148f9b43
Revises: a85172149df7
Create Date: 2021-12-13 23:21:01.377442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b609148f9b43'
down_revision = 'a85172149df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('paths', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint('paths_user_id_fkey', 'paths', type_='foreignkey')
    op.create_foreign_key(None, 'paths', 'users', ['admin_id'], ['id'])
    op.drop_column('paths', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paths', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paths', type_='foreignkey')
    op.create_foreign_key('paths_user_id_fkey', 'paths', 'users', ['user_id'], ['id'])
    op.drop_column('paths', 'admin_id')
    op.drop_table('reviews')
    # ### end Alembic commands ###
