"""empty message

Revision ID: c5f65ab0bd7b
Revises: 6d7084f4702f
Create Date: 2021-12-13 23:37:23.069074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f65ab0bd7b'
down_revision = '6d7084f4702f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paths', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("UPDATE paths SET admin_id = 1 WHERE admin_id is NULL")
    op.alter_column('paths', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE users SET password_hash_confirmation = md5(random()::text) WHERE password_hash_confirmation is NULL")
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paths', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
