"""changing from type datetime to date

Revision ID: cedc62aaf675
Revises: 44e4db9abfd6
Create Date: 2021-12-13 21:32:15.426609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedc62aaf675'
down_revision = '44e4db9abfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paths_end_date', table_name='paths')
    op.drop_index('ix_paths_initial_date', table_name='paths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paths_initial_date', 'paths', ['initial_date'], unique=False)
    op.create_index('ix_paths_end_date', 'paths', ['end_date'], unique=False)
    # ### end Alembic commands ###
