"""feat: add collumns to the table users and changed unique from descriptions

Revision ID: dae23e7e9914
Revises: c5497e7ef307
Create Date: 2021-12-08 10:26:41.417459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae23e7e9914'
down_revision = 'c5497e7ef307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_description_key', 'activities', type_='unique')
    op.drop_constraint('paths_description_key', 'paths', type_='unique')
    op.drop_constraint('points_description_key', 'points', type_='unique')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('url_image', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'url_image')
    op.drop_column('users', 'username')
    op.create_unique_constraint('points_description_key', 'points', ['description'])
    op.create_unique_constraint('paths_description_key', 'paths', ['description'])
    op.create_unique_constraint('activities_description_key', 'activities', ['description'])
    # ### end Alembic commands ###
