"""empty message

Revision ID: ed53a3d1cfda
Revises: eb9afa645638
Create Date: 2021-12-13 23:24:30.337316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed53a3d1cfda'
down_revision = 'eb9afa645638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paths', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash_confirmation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paths', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
